spring:
  datasource:
    url: jdbc:mysql://34.135.169.122:3306/villion_book?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  kafka:
    bootstrap-servers: 34.135.169.122:9092

eureka:
  client:
    service-url:
      defaultZone: http://34.121.58.202:8761/eureka
