spring:
  datasource:
    url: jdbc:mysql://localhost:3306/villion_book?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
